Add code
Ezvvin/go_final_project pull request #1
Opened 2024-07-06 04:34 UTC by Ezvvin

2024-07-06 15:41 UTC, dirtymew requested changes
Привет Павел

по коду есть замечания которые нужно исправить

по проекту хочу отметить логирование и хороший лайаут

2024-07-06 15:41 UTC, dirtymew commented on README.md
> +Создайте .env файл в корне
файл этот с дефолтными значения лучше в репозиторий положить

2024-07-06 15:41 UTC, dirtymew commented on README.md
> +
у тебя есть сборка в докере - опиши как собрать и запустить контейнер

2024-07-06 15:41 UTC, dirtymew commented on build/Dockerfile
> +EXPOSE 7540
а если порт поменяется у приложения - экспозиться будет 7540...

2024-07-06 15:41 UTC, dirtymew commented on build/Dockerfile
> +RUN GOOS=${TODO_GOOS} GOARCH=${TODO_GOARCH} go build -o /my_app ./cmd
а зачет так GOOS=${TODO_GOOS} GOARCH=${TODO_GOARCH} 

ну и определи в .env  GOOS GOARCH и все и отсуда из RUN убери...

2024-07-06 15:41 UTC, dirtymew commented on internal/nextdate/nextdate.go
> +	dateFormat := os.Getenv("TODO_DATEFORMAT")
тут не очень хорошо на каждый вызов функции делать syscall и ходить к переменным окружения - при инициализации лучше все что нужно считать и потом передать всем кому нужно...

2024-07-06 15:41 UTC, dirtymew commented on internal/db/db.go
> +	CHECK(length("title") > 0)
title и так NOT NULL - зачем CHECK

2024-07-06 15:41 UTC, dirtymew commented on internal/db/db.go
> +	PRIMARY KEY("id" AUTOINCREMENT)
можно сразу в описании поля  id INTEGER PRIMARY KEY AUTOINCREMENT,

2024-07-06 15:41 UTC, dirtymew commented on internal/db/getTasksList.go
> +	var rowsLimit = 15
лучше в константу глобальную

2024-07-06 15:41 UTC, dirtymew commented on internal/db/getTasksList.go
> +	var tasks []Task
переменные в go принято обьявлять как можно ближе к месту использования

заранее обычно не обьявляют

2024-07-06 15:41 UTC, dirtymew commented on internal/db/getTasksList.go
> +	return tasks, nil
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-07-06 15:41 UTC, dirtymew commented on internal/db/getTasksList.go
> +			log.Println(err)
лучше логировать на одном уровне - тут просто вернуть ошибку
если нужен доп контекст то стоит ошибку обернуть fmt.Errorf

2024-07-06 15:41 UTC, dirtymew commented on api/tasks.go
> +	write := func() {
а смысл в этой локальной функции? 

зачем? какую проблему она решает и почему просто не написать этот код там где ты ее вызываешь?

@Ezvvin тут такое дело   я уже у кого-то видел подобный код  - не знаю кто у кого списывает и/или где такой подход вы нашили но не стоит копировать плохие решения

2024-07-06 15:41 UTC, dirtymew commented on api/signin.go
> +		fmt.Println(os.Getenv("TODO_PASSWORD"))
нужно убрать принты и не нужно делать os.Getenv это каждый раз обращение к ОС это не быстро

2024-07-06 15:41 UTC, dirtymew commented on api/signin.go
> +	targetPassword := os.Getenv("TODO_PASSWORD")
плохо читать переменные окружения на каждый запрос 
нужно один раз при старте приложения

2024-07-06 15:41 UTC, dirtymew commented on internal/db/deleteTask.go
> +	_, err := dbHandl.GetTaskByID(id)
а зачем  2 запроса делать к бд - можно просто одним delete - тем более потом ты и так обрабатываешь RowsAffected

2024-07-06 15:41 UTC, dirtymew commented on internal/db/db.go
> +type DB struct {
это не база данных а слой асбракции над операциями - обычно такое называют storage

2024-07-06 15:41 UTC, dirtymew commented on .gitignore
> +*.env
лучше этот файл в репозиторий как раз закоммитеть

2024-07-15 10:21 UTC, dirtymew requested changes
Привет Павел

дал комментарии что еще поправить  и обрати внимание на то что с прошлого ревью осталось

2024-07-15 10:21 UTC, dirtymew commented on api/nextdate.go
> +func InitApi(storage db.Storage) {
раз ты так поделил все на файл - это я бы вынес в init.go

2024-07-15 10:21 UTC, dirtymew commented on api/putTask.go
> +	db "example/internal/db"
что -то не то с импортами

нужно использовать go imports и go fmt

импорты должны быть сгруппированы и отсортированны - см https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-07-15 10:21 UTC, dirtymew commented on api/putTask.go
> +func сheckTask(task *db.Task) error {
лучше сделать методом структуры Task

2024-07-15 10:21 UTC, dirtymew commented on api/putTask.go
> +var task db.Task
ой так не надо - нужно локальную перменную 

тут возможен конкурентный доступ

2024-07-15 10:21 UTC, dirtymew commented on internal/db/db.go
> +	CHECK(length("title") > 0)
тут прошу прощения sqlite не контролирует длину строк - нужны CHECK

2024-07-15 10:21 UTC, dirtymew commented on internal/db/getTaskByID.go
> +	row := dbHandl.db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
лучше поля явно указать чем звездочку

2024-07-15 10:21 UTC, dirtymew commented on internal/db/getTaskByID.go
> +		log.Println(err)
мб лучше логировать на уровне выше

2024-07-15 10:21 UTC, dirtymew commented on internal/db/getTasksList.go
> +	return tasks, nil
@Ezvvin тут не исправлено

2024-07-16 17:40 UTC, dirtymew requested changes
Привет Павел

критичных замечаний нет кроме того что тесты не проходят

нужно чтобы они не падали

2024-07-16 17:40 UTC, dirtymew commented on internal/db/getTasksList.go
> +			log.Println(err)
ошибки лучше логировать на одном уровне и на уровень выше

2024-07-16 17:40 UTC, dirtymew commented on config/config.go
> +	err := godotenv.Load("../.env")
лучше использовать текущую директорию - не всегда у бинарника будет доступ к директории выше

2024-07-16 17:40 UTC, dirtymew commented on README.md
> +go test ./...
тесты падают - нужно чтобы проходили

2024-07-17 19:39 UTC, Ezvvin commented on config/config.go
> +	err := godotenv.Load("../.env")
Тогда мне требуется .env файл закинуть в папку config, т.к в windows он не может найти если указать ./.env или как-то иначе.

2024-07-17 20:34 UTC, dirtymew commented on config/config.go
> +	err := godotenv.Load("../.env")
Это зависит от текущей директории. Если запускается в директории конфиг то да - но это странно. Обычно этот корневая папка проекта

2024-07-18 19:23 UTC, dirtymew approved these changes
Привет Павел

задание считаю выполненным 

Поздравляю и желаю удачи

2024-07-18 19:23 UTC, dirtymew commented on internal/db/getTasksList.go
> +		rows, err = dbHandl.db.Query("SELECT * FROM scheduler ORDER BY id LIMIT :limit",
тут стоило сделать сортировку па дате

2024-07-22 11:37 UTC, merged